### ISSUE TITLE
Command that returns > 1024 chars crashes poly

### ISSUE THREAD

**Issue by imvaskel** [ModdedMinecraftClub/polychat2#30]
It seems whenever a command returns over 1024 chars (the limit for an embed field), the server crashes. 

This can be replicated by using forge entity list.
!online does work though, weirdly.

**Comment by TraceLD** [comment]
That's due to too low buffer size which is configurable in the config and therefore it's not an issue with the code but with deployment. Closing.

**Comment by TraceLD** [comment]
What I said earlier was fake news.

**Comment by TraceLD** [comment]
Fixed by #31
